/**
 * Single source of truth for initial store state.
 * Used by the root store to initialize; slices do not duplicate state.
 */
import { getColumns } from '../selectors';

const defaultColumns = getColumns();

const defaultAgents = [
  { id: 'cursor', name: 'Cursor Agent', description: '' },
  { id: 'claude', name: 'Claude', description: '' },
  { id: 'gpt4', name: 'GPT-4', description: '' },
];

export default {
  project: { name: '', type: '' },
  features: [],
  milestones: [],
  mapNodes: [],
  users: [
    { id: 'u1', name: 'Dev' },
    { id: 'u2', name: 'Reviewer' },
  ],
  agents: defaultAgents,
  currentUser: 'u1',
  currentProjectId: '',
  defaultProjectId: '',
  projectList: [],
  projectType: '',
  actionType: '',
  planTarget: '',
  chatTopic: 'planning',
  topicMenuOpen: false,
  promptText: '',
  attachPath: '',
  attachName: '',
  editProjectName: '',
  editProjectType: '',
  editProjectSummary: '',
  editProjectAssessment: '',
  newFeatureName: '',
  newFeatureDescription: '',
  editingFeature: null,
  browseItems: [],
  browseCurrentPath: null,
  browseParentPath: null,
  browseLoading: false,
  browseError: null,
  newProjectName: '',
  viewMode: 'board',
  mainTab: 'dashboard',
  folderTree: null,
  folderExpanded: {},
  columns: defaultColumns,
  cursorWaiting: false,
  cursorPhase: 'plan',
  cursorStatusMessage: '',
  cursorStatus: [],
  cursorStreamText: '',
  cursorFileActivity: [],
  cursorAgentActivity: [],
  agentActivityExpanded: false,
  currentQuestionIndex: 0,
  cursorThinkingText: '',
  cursorAssessPrompt: '',
  cursorAssessStep: { step: 0, total: 4, label: '', message: '' },
  cursorAssessFolder: '',
  assessStreamProjectId: null,
  cursorStreamTaskId: null,
  showAssessCompleteModal: false,
  showAssessHistoryModal: false,
  assessHistory: [],
  selectedAuditEntry: null,
  pendingPlan: null,
  confirmPlanMilestoneId: '',
  pendingQuestions: null,
  pendingMilestoneQuestions: null,
  pendingMilestonePlan: null,
  milestoneOriginalPrompt: '',
  milestoneQuestionAnswers: [],
  taskTriggerQueue: [],
  taskAgentAssignments: {},
  cursorError: null,
  cursorTestResult: null,
  editingNode: null,
  editModalTab: 'details',
  reviewingNode: null,
  showNodeModal: false,
  showPromptModal: false,
  showAttachModal: false,
  showBrowseModal: false,
  showProjectModal: false,
  showAddFeatureModal: false,
  showEditFeatureModal: false,
  showNewProjectModal: false,
  dragOverColumn: null,
  chatSidebarOpen: true,
  projectChatMessages: [],
  projectChatInput: '',
  chatSelectedTaskIds: [],
  chatSelectedFeatureIds: [],
  chatSelectedFilePaths: [],
  projectChatWaiting: false,
  voiceResponseEnabled: false,
  pendingOrderedTaskIds: null,
  taskRunLogs: {},
  agentActivity: {
    live: { statusMessage: '', steps: [], files: [] },
    runLogs: {},
  },
  cursorStreamCloseRef: { current: null },
};
 